# Generated by Django 4.2.20 on 2025-05-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestUser',
        ),
    ]
